Ran 4 tests in 57.835s
FAILED (failures=1, errors=0)
test_executor_to_debugger (__main__.TestDeveloper.test_executor_to_debugger)
Traceback (most recent call last):
  File "/Users/ian/dev/projects/agents/local/seclorum/tests/test_developer.py", line 108, in test_executor_to_debugger
    self.assertEqual(status, "debugged")
AssertionError: 'tested' != 'debugged'
- tested
+ debugged


